config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lives#index'

  resources :relationships, only: [:create, :destroy]

  resources :users, only: [:edit, :update, :show]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :lights, only: [:index]
  
  resources :lives do
    resources :yells, only: [:index, :create, :destroy]
    resource :like, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  get '/searc', to:'lives#searc'
  get '/private', to:'lives#private'
  get '/family', to:'lives#family'
  get '/work', to:'lives#work'
  get '/school', to:'lives#school'
  get '/other', to:'lives#other'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :lives, dependent: :destroy
  has_many :yells

  has_many :likes, dependent: :destroy
  has_many :liked_lives, through: :likes, source: :life

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower

  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # 追記1
  has_many :follower, through: :passive_relationships, source: :use

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

  has_many :active_lights, class_name: 'Light', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_lights, class_name: 'Light', foreign_key: 'visited_id', dependent: :destroy


  def follow(other_user)
    return if self == other_user

    relationships.find_or_create_by!(follower: other_user)
  end

  def following?(user)
    followings.include?(user)
  end

  def unfollow(relathinoship_id)
    relationships.find(relathinoship_id).destroy!
  end

  def already_liked?(life)
    self.likes.exists?(life_id: life.id)
  end

  

  def create_light_follow(current_user)
    light = current_user.active_lights.new(
      visited_id: id, 
      action: 'follow'
    )
    light.save if light.valid?
  end

  def self.search(search)
    if search != ""
      User.where('name LIKE?', "%#{search}%")
    else
      User.all
    end
  end

  

  validates :name, presence: true
  with_options numericality: { other_than: 0 } do
    validates :sex
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @lives = @user.lives.order("created_at DESC")
    @users = User.all

    family = 0
    work = 0
    school = 0
    pribate = 0
    other = 0 
    @lives.each do |f|
      
      if f.tired_id == 2
        family += 1
      elsif f.tired_id == 3
        work += 1
      elsif f.tired_id == 4
        school += 1
      elsif f.tired_id == 5
        pribate += 1
      elsif f.tired_id == 6
        other += 1
      end
      
    end
    @pie = {
      "家族関係" =>  family,
      "仕事" => work,
      "学校" => school,
      "プライベート" =>  pribate,
      "それ以外" => other
    }


    lcount = 0
    @lives.each do |f|
      
      if f.likes.count != 0
        lcount += f.likes.count
      end
    end
    @lcount = lcount


    



    
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end

  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :sex)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-user-space">
  <div class="user-main-space">
    <div class="profile-space">
      <div class="acount-left">
        <div class="user-image">
          <% if @user.sex == 1 %>
            <i class="fas fa-female"></i>
            
          <% elsif @user.sex == 2 %>
            <i class="fas fa-male"></i>
          <% else %>
            <i class="fas fa-democrat"></i>
          <% end %>
        </div>
        
        
        <div class="user-show-box">

          <% if current_user.id == @user.id %>
            <div class="follow-box">
              My page
            </div>
          <% else %>
            <div class='other-acount-name'><%= @user.name %>様の投稿一覧</div>
            <div class="follow-box-2">
              <% if current_user.following?(@user) %>
                <%= button_to relationship_path(current_user.relationships.find_by(follower: @user.id)), method: :delete, class: "follow-btn" do %>
                  フォロー中
                <% end %>
              <% else %>
                <%= button_to relationships_path(follower: @user), class: "follow-btn" do %>
                  フォローする
                <% end %>
              <% end %>
              <% if current_user.following?(@user) && @user.following?(current_user) %>
                <% if @isRoom == true %>
                  <%= link_to room_path(@roomId), class: "chat-box" do %>
                    <div class="go-chat-box">
                      message
                      <i class="far fa-comments"></i>
                    </div>


                  <% end %>
                <% else %>
                  <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e| %>
                      <%= e.hidden_field :user_id, :value=> @user.id %>
                    <% end %>
                    <%= f.submit "Message?", class: "go-chat-box"%>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          <% end %>
          
        </div>

        
      </div>

      <div class="three-user-content">
        <%= link_to("#", class: 'user-status') do %>
          <p><%= @lives.count%></p>
          <span>投稿</span>
        <% end %>
        <%= link_to("#", class: 'user-status') do %>
          <p><%= @user.passive_relationships.count%></p>
          <span>フォロワー</span>
        <% end %>
        <%= link_to("#", class: 'user-status') do %>
          <p><%= @user.followings.count%></p>
          <span>フォロー中</span>
        <% end %>
      </div>
      
    </div>

    <div class="my-lives-space">
      <% @lives.each do |life| %>
        <%= render partial: "shared/lives-card", locals: { life: life } %>
      <%end %>
    </div>
    <div class="pie-space">

      <div class="pie-chart-box">
        <div class="dark-botton">
        </div>
        <%= pie_chart @pie,colors: ["rgb(0, 255, 13)",  "rgb(0, 255, 234)", "rgb(179, 255, 0)", "rgb(223, 223, 223)", "rgb(158, 158, 158)"]%>
      </div>
      <div class="pie-text">
        <% if current_user.id == @user.id%>
          <div class="pie-desc-1">Category</div>
        <% else %>
          <div class="pie-desc-2"><%= @user.name%>さんの悩みのカテゴリー割合</div>
        <% end %>
        <div class="pie-desc-2">
          <div class="pie-chart-family"><i class="fas fa-home"></i></div>
          Family
        </div>
        <div class="pie-desc-2">
          <div class="pie-chart-work"><i class="fas fa-briefcase"></i></div>
          Work
        </div>
        <div class="pie-desc-2">
          <div class="pie-chart-school"><i class="fas fa-school"></i></div>
          School
        </div>
        <div class="pie-desc-2">
          <div class="pie-chart-private"><i class="fas fa-person-booth"></i></div>
          Private
        </div>
        <div class="pie-desc-2">
          <div class="pie-chart-other"><i class="fas fa-otter"></i></div>
          Other
        </div>


          
      </div>
    </div>
    
    
    
    
  </div>
  

</div>