config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lives#index'

  resources :relationships, only: [:create, :destroy]

  resources :users, only: [:edit, :update, :show]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :lights, only: [:index]
  
  resources :lives do
    resources :yells, only: [:index, :create, :destroy]
    resource :like, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  get '/searc', to:'lives#searc'
  get '/private', to:'lives#private'
  get '/family', to:'lives#family'
  get '/work', to:'lives#work'
  get '/school', to:'lives#school'
  get '/other', to:'lives#other'

end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show]

  def index
    @lives = Life.all.order("created_at DESC")
    @count = @lives.includes(:likes).sort {|a,b| b.likes.size <=> a.likes.size}
    @yell = @lives.includes(:yells).sort {|a,b| b.yells.size <=> a.yells.size}
  end

  def show
    @life = Life.find(params[:id])
    @yell = Yell.new
    @yells = @life.yells
  end

  def new
    @life = Life.new
  end

  def create
    @life = Life.new(life_params)
    if @life.save
      redirect_to root_path
    else
      render :new
    end
  end

  
  def destroy
    @life = Life.find(params[:id])
    @life.destroy
    redirect_to root_path
  end

  def searc
  end

  def search
    @lives = Life.search(params[:keyword])
    @users = User.search(params[:keyword])
  end

  def family
    @lives = Life.where(tired_id:2).order('created_at DESC')
    render action: "search"
  end

  def work
    @lives = Life.where(tired_id:3).order('created_at DESC')
    render action: "search"
  end

  def school
    @lives = Life.where(tired_id:4).order('created_at DESC')
    render action: "search"
  end

  def private
    @lives = Life.where(tired_id:5).order('created_at DESC')
    render action: "search"
  end

  def other
    @lives = Life.where(tired_id:6).order('created_at DESC')
    render action: "search"
  end

  private

  

  def life_params
    params.require(:life).permit(:title, :bad_thing, :hope, :tired_id, :how_long_id, :want_id, :month_id).merge(user_id: current_user.id)
  end


end

app/helpers/lives_helper.rb
module LivesHelper
end

app/views/lives/index.html.erb
<div class="all-index-space">
  <div class="main-index-page">


    <div class="index-top-1">
      <i class="far fa-comment-alt"></i><p>New</p>
    </div>
    <div class="bxslider">
      <div class="test-box-parent">
        <% if @lives.count >= 1 %>
          <% @first = @lives.slice(0,8)%>
          <% @first.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
      <div class="test-box-parent">
        <% if @lives.count >= 9 %>
          <% @second = @lives.slice(8,8)%>
          <% @second.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
      <div class="test-box-parent">
        <% if @lives.count >= 17 %>
          <% @third = @lives.slice(16,8)%>
          <% @third.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="index-top-1">
      <i class="far fa-heart"></i><p>Like</p>
    </div>
    <div class="bxslider">
      <div class="test-box-parent">
        <% if @lives.count >= 1 %>
          <% @first = @count.slice(0,8)%>
          <% @first.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
      <div class="test-box-parent">
        <% if @lives.count >= 9 %>
          <% @second = @count.slice(8,8)%>
          <% @second.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
      <div class="test-box-parent">
        <% if @lives.count >= 17 %>
          <% @third = @count.slice(16,8)%>
          <% @third.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="index-top-1">
      <i class="far fa-comment"></i><p>Yell</p>
    </div>
    <div class="bxslider">
      <div class="test-box-parent">
        <% if @lives.count >= 1 %>
          <% @first = @yell.slice(0,8)%>
          <% @first.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
      <div class="test-box-parent">
        <% if @lives.count >= 9 %>
          <% @second = @yell.slice(8,8)%>
          <% @second.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
      <div class="test-box-parent">
        <% if @lives.count >= 17 %>
          <% @third = @yell.slice(16,8)%>
          <% @third.first(8).each do |life| %>
            <%= render partial: "shared/lives-puts-card", locals: { life: life } %>
          <% end %>
        <% end %>
      </div>
    </div>
    
  </div>
</div>

app/views/lives/new.html.erb
<div class="new-lives-space">
  <div class="lives-main-space">

    <%= form_with model: @life, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <div class="lives-title-space">
      <a>Write your Problem</a>
      <div class="advice-box">
        <p>今日もお疲れ様です。嫌なことやしんどいことは書き出してみると楽になるかもしれません。<p>
      </div>
      <div class="title-space">
        <div class="title-top-space">
          <div class="title-box">
            <%= image_tag 'title.png' , size: '45x45' ,class: "title-icon" %>
          </div>
          <p>Title</p>
        </div>
        <%= f.text_area :title, class:"title-text", id:"item-info", placeholder: "タイトルを入力してください",rows:"1" ,maxlength:"30" %>
      </div>
    </div>

    

    <div class="select-box-space">
      
      <div class="select-box-main">
        <div class="chose-box">
          <%= image_tag 'time.png' , size: '60x60' ,class: "select-icon" %>
        </div>
        <span>HowLong</span>
        <%= f.collection_select(:how_long_id, HowLong.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>

      <div class="select-box-main">
        <div class="chose-box">
          <%= image_tag 'tired.png' , size: '60x60' ,class: "select-icon" %>
        </div>
        <span>Tired</span>
        <%= f.collection_select(:tired_id, Tired.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>

      <div class="select-box-main">
        <div class="chose-box">
          <%= image_tag 'want.png' , size: '60x60' ,class: "select-icon" %>
        </div>
        <span>Want</span>
        <%= f.collection_select(:want_id, Want.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>


      <div class="select-box-main">
        <div class="chose-box">
          <%= image_tag 'season.png' , size: '60x60' ,class: "select-icon" %>
        </div>
        <span>Season</span>
        <%= f.collection_select(:month_id, Month.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
      
    </div>

    <div class="writing-space">
      <div class="new-text-space">
        <div class="text-icon">
          <%= image_tag 'sad.png' , size: '60x60' ,class: "select-icon" %>
        </div>
        <%= f.text_area :bad_thing, class:"lives-text", id:"item-info", placeholder: placeholder,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="new-text-space">
        <div class="text-icon">
          <%= image_tag 'hope.png' , size: '60x60' ,class: "select-icon" %>
        </div>
        <%= f.text_area :hope, class:"lives-text", id:"item-info", placeholder: badholder ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <div class="new-btn">
      <%= f.submit "Post" ,class:"post-btn" %>
      <div class="cansel-space">
        <%=link_to 'Cansel', root_path, class:"back-btn" %>
      </div>
    </div>
    <% end %>
    
    
  </div>
</div>

app/views/lives/searc.html.erb
<div class="searc-main">
  <div class="searc-box">

    <%= form_with(url: search_lives_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "悩みを検索", class: "search-input" %>
      <%= button_tag type:'submit', class: "search-btn" do %>
        <i class="fas fa-search-plus"></i>
      <% end %>
    <% end %>

    <div class="search-btn-box">

      <div class="search-desc-2">
        <%= link_to family_path, class: "search-icon" do %>
        
        <p>Family</p>
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to work_path, class: "search-icon" do %>
        
        Work
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to school_path, class: "search-icon" do %>
        
        School
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to school_path, class: "search-icon" do %>
        
        Private
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to family_path, class: "search-icon" do %>
        
        Other
        <% end %>
      </div>

    </div>

    <div class="search-index-first">
      <div class="search-x">
        <i class="far fa-edit" ></i>
        <p class="searc-life-hint">自分が悩んでいるワードやカテゴリーで検索してみましょう。</p>
        <p class="searc-life-hint">自分意外にも同じ悩みを持っていることを知ると、少しは元気が出るかもしれません。</p>

      </div>
      <div class="search-x">
        <i class="fas fa-users"></i>
        <p class="searc-life-hint">上記フォームからユーザーを検索することもできます。</p>
      </div>
    </div>

  </div>
</div>

app/views/lives/search.html.erb
<div class="search-main">
  <div class="search-box">

    <%= form_with(url: search_lives_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "悩みを検索", class: "search-input" %>
      <%= button_tag type:'submit', class: "search-btn" do %>
        <i class="fas fa-search-plus"></i>
      <% end %>
    <% end %>

    <div class="search-btn-box">

      <div class="search-desc-2">
        <%= link_to family_path, class: "search-icon" do %>
        
        <p>Family</p>
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to work_path, class: "search-icon" do %>
        
        Work
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to school_path, class: "search-icon" do %>
        
        School
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to school_path, class: "search-icon" do %>
        
        Private
        <% end %>
      </div>

      <div class="search-desc-2">
        <%= link_to family_path, class: "search-icon" do %>
        
        Other
        <% end %>
      </div>

    </div>

    <div class="search-icon-select">
      <div class="edit-lives-icon" id="lives-line">
        <i class="far fa-edit" id="lives"></i>
      </div>
      <div class="edit-users-icon" id="user-line">
        <i class="fas fa-users" id="users"></i>
      </div>
    </div>

    

    

    <div class="search-lives-main" id="life">
      <% if @lives.length != 0%>
        <div class="search-body-space">
          <p class="search-life-d">・検索に<%= @lives.length%>件ヒット</p>
          <%= render "shared/show_life"%>
        </div>
      <% else %>
        <div class="search-sorry">
          <div class="sorry-sentence">
            <a class="sorry-d">No Data</a>
            <p class="sorry-p">・お探しになられていた悩みは見つかりませんでした。</p>
            <p class="sorry-p">・検索ワードを短くすると見つけることができるかもしれません。</p>
          </div>
        </div>
      <% end %>
      <div class="search-user-main" id="user">
        <% if @users.present? && @users.length != 0%>
          <%= render "shared/show_user"%>
        <% else %>
          <div class="search-sorry">
            <div class="sorry-sentence">
              <a class="sorry-d">No User</a>
              <p class="sorry-p">・該当するユーザーは見つかりませんでした。</p>
              <p class="sorry-p">・検索ワードを短くすると見つけることができるかもしれません。</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>


    

  </div>
</div>

app/views/lives/show.html.erb
<div class="show-lives-space">
  <div class="lives-main-space">
    <div class="title-lives-box">
      <div class="life-titile-left">
        <div class="life-title-text">
          <div class="title-1">
            Title:
          </div>
          
          
          <div class="title-2">
            <%= @life.title.truncate(10) %>
          </div>
        </div>
        <div class="life-title-owner">
          <% if current_user.id == @life.user.id %>
          <p class="sub-text-a">過去の悩み</p>
          <% else %>
            投稿者:
            <%= link_to  "/users/#{@life.user.id}", class: "owner-pass" do %>
              <%= @life.user.name%>
            <% end %>
          <%end%>
        </div>
      </div>
    </div>
    <div class="lives-text-box">





      <div class="lives-double-text">
        <div class="top-double">
          <div class="lives-text-titile">
            <%= image_tag 'sading.png' , size: '50x50' ,class: "top-icon" %>
          </div>
          <div class="lives-title-big">
            Problem
          </div>
        </div>
          <a class="lives-text-under"><%= @life.bad_thing%></a>
      </div>

      <div class="lives-double-text">
        <div class="top-double">
          <div class="lives-text-titile">
            <%= image_tag 'happy.png' , size: '50x50' ,class: "top-icon" %>
          </div>
          <div class="lives-title-vig">
            mini happy
          </div>
        </div>
          <a class="lives-text-under"><%= @life.bad_thing%></a>
      </div>






    </div>
    <div class="lives-category-box">
      <%= render partial: 'shared/lives_category', locals: { life: @life } %>
      <div class="life-title-right">
        <% if current_user.id == @life.user.id %>
          <div class="me-to-count">
            <i class="far fa-heart"></i>
            <%= @life.likes.count %>
          </div>
        <% else %>
          <% if current_user.already_liked?(@life) %>
            <%= link_to life_like_path(@life), method: :DELETE, class: "like-icon"  do %>
              <i class="fas fa-heart"></i>
            <% end %>
          <% else %>
            <%= link_to life_like_path(@life), method: :POST, class: "cansel-icon" do %>
              <i class="far fa-heart"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    
    
    <div class="lives-comment-box">
      <%= form_with model: [@life, @yell], class: 'yell-form', id: "form", local: true do |f| %>
        <div class="errors-box">
          <%= render 'shared/error_messages', model: f.object %>
        </div>
        <div class="form-input">
          <%= f.text_area :content, class: 'form-yell', placeholder: yellholder, rows:"7", id: "content" %>
        </div>
        <%= f.submit '送信', class: 'yell-submit', id: "submit" %>
      <% end %>
      <div class="yell-lists">
        <% @yells.each do |yell| %>
          <div class="yell-content">
            <%= yell.content%>
            <div class="yell-created">
              <%= time_ago_in_words(yell.created_at) %>前
            </div>
          </div>
        <% end %>
      </div>
      
    </div>
    



  </div>
  
</div>