config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lives#index'

  resources :relationships, only: [:create, :destroy]

  resources :users, only: [:edit, :update, :show]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :lights, only: [:index]
  
  resources :lives do
    resources :yells, only: [:index, :create, :destroy]
    resource :like, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  get '/searc', to:'lives#searc'
  get '/private', to:'lives#private'
  get '/family', to:'lives#family'
  get '/work', to:'lives#work'
  get '/school', to:'lives#school'
  get '/other', to:'lives#other'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Life Count</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

    <script>
      $(document).ready(function(){
        $('.bxslider').bxSlider({
          speed: 600,
          minSlides: 2,
          maxSlides: 2,
          touchEnabled: false
        });
      });
    </script>

  </head>

  <header>
    <div class="top-header-space">
      <div class="app-icon-box">
        <%= link_to( "/", class: "app-title" ) do %>
          <h1 class="title">
            <span>L</span>
            <span>i</span>
            <span>f</span>
            <span>e</span>
            <span>&nbsp;</span>
            <span>C</span>
            <span>o</span>
            <span>u</span>
            <span>n</span>
            <span>t</span>
          </h1>
        <% end %>
      </div>
      

      <div class="left-icon">

        <%= link_to(new_life_path, class: "logout") do %>
          <i class="far fa-edit"></i>
        <% end %>

        <%= link_to(lights_path, class: "logout") do %>
          <i class="far fa-bell"></i>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to(destroy_user_session_path, method: :delete, class: "logout") do %>
            <i class="fas fa-door-open"></i>
          <% end %>
        <% else %>
          <%= link_to(new_user_session_path, class: "logout") do %>
            <i class="fas fa-door-closed"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </header>
  <body>
    <%= yield %>
  </body>
  <footer>
    <%= link_to("/", class: 'top-icon-btn') do %>
      <%= image_tag 'home.png' , size: '60x60' ,class: "under-icon" %>
    <% end %>
    
    <%= link_to(searc_path) do %>
      <%= image_tag 'search-word.png' , size: '60x60' ,class: "under-icon" %>
    <% end %>
    
    <% if user_signed_in? %>
      <%= link_to("/users/#{current_user.id}", class: 'top-icon-btn') do %>
        <%= image_tag 'my-page.png' , size: '60x60' ,class: "under-icon" %>
      <% end %>
    <% else %>
      <%= link_to("/", class: 'top-icon-btn') do %>
        <%= image_tag 'my-page.png' , size: '60x60' ,class: "under-icon" %>
      <% end %>
    <% end %>
  </footer>
</html>